### PR TITLE
Fix incompatible release

### PR DESCRIPTION
**Pull request by robertcoltheart**
None of the below fixes anything. The search continues...

### CODE REVIEW

**Comment by robertcoltheart** [comment]
Paging @matkoch, do you know what R# is doing when it says a plugin is "incompatible"?

**Comment by robertcoltheart** [comment]
If I disable the "extension verifier" option in R#, then the plugin installs just fine 🤷

**Comment by matkoch** [comment]
Could you try just setting `[222.0.0]` as the wave version? Theoretically, that shouldn't matter, but it's the current standard. I'll also ask internally.

**Comment by matkoch** [comment]
@robertcoltheart could you gather the following information for us?

1. `%LocalAppData%\JetBrains\Shared\vAny\Installer\InstallLog_[InstallationTime].log`
2. `%LocalAppData%\JetBrains\ReSharperPlatformVs17\vAny_[InstanceId][RootSuffix]\packages.config`
3. `%LocalAppData%\JetBrains\Installations\ReSharperPlatformVs17_[InstanceId][RootSuffix]\ExtensionVerificationReport.json`

**Comment by robertcoltheart** [comment]
@matkoch Here you go. This was after I changed the Wave to be [222.0.0].

[InstallLog_2022-08-08T06-22-44.txt](https://github.com/machine/machine.specifications.runner.resharper/files/9277515/InstallLog_2022-08-08T06-22-44.txt)
[packages.txt](https://github.com/machine/machine.specifications.runner.resharper/files/9277516/packages.txt)
[ExtensionVerificationReport.json.txt](https://github.com/machine/machine.specifications.runner.resharper/files/9277520/ExtensionVerificationReport.json.txt)

**Comment by robertcoltheart** [comment]
@matkoch The main issues I see in the log file:

1. Obsolete code failures - This should be solvable, just migrate the code to use non-obsolete code
2. Failure to load `Machine.Specifications.dll` - I can solve this too by using Reflection to load the types I need
3. `Could not load referenced assembly 0x23000002 “JetBrains.ReSharper.TestRunner.Abstractions` - I'm referencing this assembly via Nuget because I need the `RemoteTask`, `ITestDiscoverer` and `ITestExecutor` types and other unit-test specific types used for unit test providers. But I can't bundle this in my extension package because this is an assembly provided by the R# installation.

I can solve items 1 and 2, but 3 is a deal breaker, I don't know why the R# verifier is complaining that it can't find this assembly, given that the assembly is right there in the installation folder. I can't bundle it in the extension package, and it isn't provided by the `Resharper.SDK` set of nuget packages.

See https://www.nuget.org/packages/JetBrains.ReSharper.TestRunner.Abstractions

**Comment by robertcoltheart** [comment]
> isn't provided by the Resharper.SDK set of nuget packages.

I should be clear. It _is_ provided in the `Resharper.SDK`, however the TFM for `Resharper.SDK` is only `netframework`, and the unit test provider adapter needs to target both `netframework` and `netstandard`, which means I get compile errors if I try and reference the `Resharper.SDK` package from my `netstandard` adapter project.

**Comment by ulex** [comment]
@robertcoltheart just a small update: we are fixing the API verifier. Since version 2022.2.2 (I hope), it will only check bindings for JetBrains* assemblies, so you can continue to use static binding as before. 
the issue 3 is also being fixed

**Comment by robertcoltheart** [comment]
Thanks for the update @ulex, keep me posted on the fixes please 👍

**Comment by ulex** [comment]
@robertcoltheart the fix has arrived to the branch which is designated for 2022.2.2 bug fix. Its ETA is next week

**Comment by robertcoltheart** [comment]
Ok great, thanks. I'll look for it next week.

**Pull request merged**
