### PR TITLE
[Feature] Support for R# 2018.2

### PR DESCRIPTION
**Pull request by robertcoltheart**
~~Not yet tested, not ready for release yet.~~

Surprisingly it works after some initial testing.

Caveats:
- Moves to new csproj format. I'm so tired of updating R# with the old format, it almost never works. At least this way it can do it manually with very little effort.
- Tests are disabled because of the above, as R# SDK uses Nunit v2, whereas new csproj requires Nunit v3. Will look to see what can be done, but to be honest I never felt like the tests added huge value, so I'm not sad if they disappear.
- Updates the way we do versioning and release notes. No longer need to update appveyor.yml, just do it all via Github releases.

@ivanz

### CODE REVIEW

**Comment by ivanz** [comment]
Hey,

I am not around much nowadays, nor have I used .Net in more than 1 year, so consider yourself a maintainer of this repo. I've just updated your membership permissions to reflect that and be an admin of this repo and a maintainer in the GitHub org resharper team.


As such, I don't really feel qualified to make a review on this one, however I do recommend adding instructions in the README or wiki on how the release is managed now, so that it's well documented for future reference if someone else need to do it.

**Comment by robertcoltheart** [comment]
Thank @ivanz

**Comment by robertcoltheart** [comment]
@citizenmatt Do you know if there's a way to be notified when there is a new R# SDK to target? We always seem to be caught on the back foot with updating and have to scramble to get a release out.

**Comment by ulrichb** [comment]
@robertcoltheart I use this [feed](https://blog.jetbrains.com/dotnet/) to get informed when an EAP phase starts (e.g. blog post for [2018.2](https://blog.jetbrains.com/dotnet/2018/07/02/introducing-resharper-ultimate-2018-2-early-access-program/)).

**Comment by robertcoltheart** [comment]
Thanks both

**Comment by matkoch** [comment]
@robertcoltheart it seems you've been using parts from the template I'm currently working on. If you have any feedback to tell, please do :)

**Comment by robertcoltheart** [comment]
Ha thanks, I've found them pretty useful so far. I adapted them a bit. Only quirky thing I found so far is that the install can sometimes pick up multiple directories if a hive has been installed for multiple versions of R#. Somehow it needs to take the latest (?) version directory or at least the version that matches the installer.

**Comment by matkoch** [comment]
Hi Robert, thanks for your feedback. Yes that part is a bit tricky, but I assume you had an existing installation before already, right?

**Pull request merged**
