### PR TITLE
Support R# 2016.3

### PR DESCRIPTION
**Pull request by robertcoltheart**
Really painful upgrade this time, Nuget would not upgrade directly and instead I had to uninstall all packages and re-install.

Also please note I had to upgrade the assembly target framework from 4.0 to 4.6 as well. Shouldn't be an issue.

@citizenmatt Not sure about all the `TargetFrameworkId.Default` code everywhere. I couldn't really see what else to use when calling `IUnitTestElementIdFactory.Create`.

### CODE REVIEW

**Comment by citizenmatt** [comment]
I'm hitting this issue with nuget update, too. I don't know what's going on - nuget is complaining about being unable to find packages of a certain version that in some cases are already installed. And yet install fresh works fine. We're looking into it. Apologies.

**Comment by citizenmatt** [comment]
You should use `IUnitTestElementsObserver.TargetFrameworkId` when creating test elements.

`TargetFrameworkId.Default` is essentially fine for a standard .net project - it basically means the target framework for the current project, which would be something like .net 4.6.2. It's really useful for .net core projects, which can have multiple targets, e.g. core clr or .net 4.6.2. 

Testing will run discovery for all target frameworks, and add multiple tests per test method, one for each applicable target framework, and the correct framework ID is passed in with the `IUnitTestElementsObserver`.

**Comment by robertcoltheart** [comment]
@citizenmatt Thanks, I've updated the code per your suggestions.

**Comment by citizenmatt** [comment]
Looks good to me!

**Comment by ivanz** [comment]
@robertcoltheart Thanks for this! I have added you to the Machine github organization and if you accept the invitation you will have full write access to this repo and merge the pull request 🎉  🎅

**Comment by robertcoltheart** [comment]
Thanks @ivanz. I need a review approval on this though before I can merge, @citizenmatt maybe you could provide?

**Comment by citizenmatt** [comment]
I've approved the changes, looks good to merge, as far as I can tell.

**Comment by robertcoltheart** [comment]
@ivanz There's something blocking the merge, looks like one of the Appveyor builds just stays 'pending' and never runs.

**Comment by ivanz** [comment]
@robertcoltheart  Sorry about that. I think there was an extra check for the master branch which never triggered through the integration in AppVeyor, so I have removed it and it should be good to go now.

If you want to release once merged you will need to:

1. Adjust the versions and pre-release value (true/false) here: https://github.com/machine/machine.specifications.runner.resharper/blob/master/appveyor.yml#L2
2. Update release notes here: https://github.com/machine/machine.specifications.runner.resharper/blob/master/appveyor.yml#L38 
3. Create tag e.g. "vX.Y.X"

That will trigger a NuGet package to be pushed to the resharper plugins NuGet repo and also a GitHub release.

Any issues - let me know (Might be some delay in my responses since I am travelling right now)

**Comment by robertcoltheart** [comment]
Also, @citizenmatt this is a side issue, but debugging a R# plugin is massively complicated. Would be good to have the /Resharper.Plugin command line args back again or something similar, so that the solution can be "F5 compliant" from within VS.

**Comment by citizenmatt** [comment]
Yeah, initial setup is a pain. You can make it a whole lot smoother, but it requires a few steps up front. You need to build and install the plugin once, and then use the `<HostFullIdentifier>` element in your `.csproj` (or `.csproj.user`) file to specify the name of an installation, and ReSharper's msbuild tasks will automatically copy the latest build to the install of that name. You can see the list of installations in `%LOCALAPPDATA%\JetBrains\Installations`. Ignore any that has `_000` or `_001` at the end - these are copies that are made during installation if the original is locked at all. They get cleaned up at some point.

This is [described in more detail in the devguide](https://www.jetbrains.com/help/resharper/sdk/Extensions/Deployment/LocalInstallation/CopyOnBuild.html).

**Pull request merged**
