### PR TITLE
[Feature] Add reflection navigation to unify PSI and metadata

### PR DESCRIPTION
**Pull request by robertcoltheart**
__Context__
I'm 90% complete with the code for `dotnet core` (see #46), but the change is so large I want to break it up into smaller PRs to make it easier to review. This is the first of those changes.

__Description__
The idea for this change is taken from the Xunit provider, which uses a series of reflection APIs to unify the PSI and metadata code for detecting test cases and classes. For those unfamiliar, PSI is the tree structure of the code itself, and the metadata is taken from the compiled DLLs and PDBs. We need a way to identify tests using both methods.

I've also found a neat way of performing PSI and metadata unit testing using the Resharper SDK. I'll be adding to this with subsequent PRs.

**What's next**
Metadata parsing code and tests

**Edit:**
This is ready for review. Things added:
- No functional code changed, just added additional detection methods that will replace the code in `PsiExtensions` and `MetadataExtensions`.
- Unit testing added
- PSI parsing code added

Paging @ivanz

### CODE REVIEW

**Comment by ivanz** [comment]
Had a scan and it looks good to me. Slightly got thrown off by the use of `TypeInfo` which is different than the .NET defined core `TypeInfo` type when I was scanning through. Heads up from me - I haven't messed around much with the guts of the ReSharper runner myself nor have a I done any previous ReSharper plugin work, so won't be of much help in that department for reviews. Nice job so far 👍

**Comment by robertcoltheart** [comment]
@ivanz I'm open to suggestions on naming? The Xunit provider uses the terminology `ITypeInfo`, `IFieldInfo`, `IAttributeInfo`, `IMethodInfo` to describe the various components of the classes, and I've copied its naming structure here. Be assured I've spent quite a bit of time in the ReSharper world at this point (!), so I'm pretty comfortable with where this change is headed.

**Comment by robertcoltheart** [comment]
If you're happy can I get a 👍 to merge, and I'll put the next PR up? Tagging @citizenmatt as well.

**Comment by robertcoltheart** [comment]
In it goes...

**Pull request merged**
