### PR TITLE
Fix behaviors for test runner

### PR DESCRIPTION
**Pull request by robertcoltheart**
Also converts behaviors into theory-like nodes in R#, as this will fix the long-standing issue of having multiple run context icons on the behavior field within R#.

### CODE REVIEW

**Comment by mikeblakeuk** [comment]
Looking forward to this :)

**Comment by mikeblakeuk** [comment]
Really looking forward to this

**Comment by robertcoltheart** [comment]
This is complete, just need another day to do some final testing.

**Comment by nmosafi** [comment]
@robertcoltheart Any idea how to start using this?

**Comment by robertcoltheart** [comment]
Once Jetbrains approves the plugin update, it will be available in the Rider plugins menu as usual.

**Comment by nmosafi** [comment]
Thanks @robertcoltheart - I see a new version 2021.3.2 however upon upgrading Rider no longer detects any tests at all. Any idea how I can diagnose what's gone wrong? Thanks

**Comment by robertcoltheart** [comment]
I'm not seeing this behavior, can you provide a sample solution to test against? Does it work if you open it under VS with ReSharper installed and the MSpec plugin? Try reinstalling the plugin in Rider.

**Comment by nmosafi** [comment]
Thanks... reinstalling seems to have helped, strangely!

Have a nice weekend

**Pull request merged**
