### PR TITLE
[Feature] Update to R# 2020.2

### PR DESCRIPTION
**Pull request by robertcoltheart**
**JetBrains:** "Revamped test runner!!"

**Plugin developers:** _sigh_ Why am I still doing this.

Relies on: https://github.com/machine/machine.specifications/pull/414

### CODE REVIEW

**Comment by StephenRobin** [comment]
~Hi @robertcoltheart.  I'd like to help test this in Rider, but I'm new to ReSharper / Rider plugin development.  Have you any instructions for how to build, run and debug this in Rider?

**Comment by derekgreer** [comment]
Thanks for this

**Comment by robertcoltheart** [comment]
@StephenRobin This is a few days yet from being able to be tested. JetBrains have completely re-written their unit test SDK, so I'm basically having to re-code 60% of this plugin. There are instructions on the Readme for how to debug in your local environment.

**Comment by robertcoltheart** [comment]
Just to set expectations, this is a much bigger change than I anticipated and is going to require some changes in the core MSpec libraries and utility package.

@citizenmatt I really wish we'd been given a heads-up on this breaking change to the SDK.

**Comment by derekgreer** [comment]
So, does merged into master mean released for this project?  I'm not seeing it show up yet under the Resharper Extensions.

**Comment by robertcoltheart** [comment]
No, check the releases page for when this will be released. I'll also update here when it is available in the extensions feed.

**Pull request merged**
