### PR TITLE
Support R# 2016.2

### LINKED ISSUE #43: Support ReSharper 2016.2
No mspec tests are picked up in ReSharper 2016.2

### PR DESCRIPTION
**Pull request by robertcoltheart**
Fixes #43.

Needs checking to make sure everything still works, but my initial check showed that all tests are discovered and run correctly.

@citizenmatt if you have time, please take a look to see I've done this correctly.

### CODE REVIEW

**Comment by citizenmatt** [comment]
Nice work! I'll take a look ASAP, either today or tomorrow. Thanks!

Have you seen #41? Are you interested in helping out? I'm sure @bluerobotch would welcome someone new :)

**Comment by ivanz** [comment]
Curious here if there is a specific reason why the plugin is pulling individual ReSharper nuget packages instead of the [the big bang JetBrains.ReSharper.SDK one](https://www.nuget.org/packages/JetBrains.ReSharper.SDK)?

**Comment by citizenmatt** [comment]
It is [pulling in JetBrains.ReSharper.SDK](https://github.com/machine/machine.specifications.runner.resharper/pull/44/files#diff-e5d3d5720e37cf8a161fde9d84212415R37), it's just that nuget adds all dependencies as separate packages in packages.config, rather than just the top level dependencies. That's one of the nice things project.json has going for it.

**Comment by robertcoltheart** [comment]
@citizenmatt Sure, I'd be interested in helping out here and there. I'm actively using this R# extension, so I'm happy to help keep it updated with future R# releases.

**Comment by ricardoborges** [comment]
Hey guys, 

I'm facing the same problem, but happy to find this pull request! Good job!

I'm looking foward to this release.

**Comment by mikeblakeuk** [comment]
Is there a build for this we can play with?

**Comment by ivanz** [comment]
You can follow those steps to get your own build until @citizenmatt  approves and merges the pull request: https://github.com/machine/machine.specifications.runner.resharper/wiki

**Comment by citizenmatt** [comment]
Hey. Sorry for the delay. This looks good to me. I haven't run it or installed it, but if it's working for you, that sounds good.

The only change I'd suggest is to update the version for the .nuspec file. It's a variable at the minute, and I don't know where the value comes from.

Who's going to merge and release?

**Comment by robertcoltheart** [comment]
@citizenmatt The version comes from the `rakefile.vb` build script when it calls `nuget pack`.

**Comment by iancooper** [comment]
I tried a local build as per the wiki, though the rake script failed and I had to nuget pack manually; but can't seem to get 2016.2 to recognize the locally built package though 2016.1 will. I guess that means that I have failed with a setting to tell R# that this is intended for that version. But I don't know where to set that...

**Comment by iancooper** [comment]
PS Why is this important. R# 2016.2 is far better with dotnetcore projects than 2016.1 so its better to have that installed, but you lose the testrunner for all projects (not just any dotnetcore ones) because there is no integration. I'd use a local package, but I can't figure out how to get it building from the wiki.

I'd pitch in to help, but I have so much to learn before I can contribute effectively here right now.

**Comment by AnonymousRetard** [comment]
Hello Ian. I have successfully created and installed a local build with the help from the wiki.
To me it sounds like you've built the master branch instead of the branch from robertcoltheart with these changes: https://github.com/machine/machine.specifications.runner.resharper/pull/44/commits/c496be19618b7b062fd2c9ef589ea944b7802554

This is the repository that you have to git clone: https://github.com/robertcoltheart/machine.specifications.runner.resharper/tree/feature/upgrade-resharper-version

As soon as someone merges this it will end up in the master branch and hopefully they will release an official nuget package as well.

**Comment by iancooper** [comment]
@AnonymousRetard Ah, thanks for that. Let me try.

**Comment by citizenmatt** [comment]
Is there anyone from the core team looking at this? Anyone going to merge and release?

I seem to have commit rights (don't remember when that happened!), so I can do it, and/or I can add someone else to the team.

Shall I do it?

**Comment by ivanz** [comment]
I've released 1.6.0-beta5 with this change to the ReSharper gallery. However it doesn't seem to discover tests in dotnet cli projects still. Thanks @robertcoltheart for the contribution!

As part of doing that I removed the Ruby build and shifted the CI to AppVeyor: https://ci.appveyor.com/project/machine-specifications/machine-specifications-runner-resharper

**Comment by citizenmatt** [comment]
Thanks @ivanz, @robertcoltheart!

I'll comment on #46 about .net core tests.

**Pull request merged**
