### PR TITLE
Upgrade R# to 2021.3

### PR DESCRIPTION
**Pull request by robertcoltheart**
*Sigh* another set of wonderful breaking changes from the geniuses at JB.

### CODE REVIEW

**Comment by mikeblakeuk** [comment]
Using VS2022 17.0.2 with R# 2022.3 windows 10

image

We do have "some" Behavior tests so don't want to migrate them yet. 

```

System.InvalidCastException: Unable to cast object of type 'Machine.Specifications.Runner.ReSharper.Elements.MspecContextSpecificationTestElement' to type 'Machine.Specifications.Runner.ReSharper.Elements.MspecBehaviorSpecificationTestElement'.
   at Machine.Specifications.Runner.ReSharper.UnitTestElementFactory.GetOrCreateBehaviorSpecification(MspecBehaviorTestElement behavior, String fieldName, String ignoreReason)
   at Machine.Specifications.Runner.ReSharper.MspecTestMetadataExplorer.ExploreBehavior(MspecContextTestElement contextElement, IFieldInfo field)
   at Machine.Specifications.Runner.ReSharper.MspecTestMetadataExplorer.ExploreContext(ITypeInfo type)
   at Machine.Specifications.Runner.ReSharper.MspecTestMetadataExplorer.ExploreAssembly(IMetadataAssembly assembly, CancellationToken token)
   at JetBrains.ReSharper.UnitTestFramework.Exploration.Artifacts.MetadataElementsSource.ExploreProject(IProject project, FileSystemPath outputPath, MetadataLoader loader, ILogger logger, CancellationToken cancellationToken, Action`1 exploreAssembly)
   at Machine.Specifications.Runner.ReSharper.MspecTestExplorerFromMetadata.ProcessProject(MetadataLoader loader, IUnitTestElementObserver observer, CancellationToken token)
   at JetBrains.ReSharper.UnitTestFramework.Exploration.Artifacts.UnitTestExplorerFrom.Metadata.ProcessProjectCore(IUnitTestElementObserver observer, CancellationToken token)
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at JetBrains.ReSharper.UnitTestFramework.Exploration.Artifacts.UnitTestExplorerFrom.DotNetArtifacts.Async.<ProcessArtifact>d__2.MoveNext()
```

**Comment by robertcoltheart** [comment]
Will take a look.

Behaviors will be supported for the time being, probably beyond v2. For v3 I'm planning on introducing `Examples` which will (possibly) deprecate behaviors, see https://github.com/machine/machine.specifications/issues/141

**Comment by mikeblakeuk** [comment]
Hi,

Any news on this? Thanks

**Comment by robertcoltheart** [comment]
Unfortunately it isn't a simple fix, I have a branch in progress but need more time to finish it.

**Comment by mikeblakeuk** [comment]
OK. Thank you for looking. It is blocking our vs2022 / rider upgrade.

**Comment by mikeblakeuk** [comment]
Tracked here https://github.com/machine/machine.specifications/issues/459

**Pull request merged**
